Fixed DB Connection Sensor
orca-services/cakephp-heartbeat pull request #13
Opened 2018-11-20 10:12 UTC by liviascapin

I noticed that the DB Connection Sensor is not working as expected.

2018-12-12 11:05 UTC, ravage84 commented
@liviascapin  what do you mean by "not working as expected"?
What is our expectation? I don't think we clearly have defined it.
The class doc block doesn't say anything how it should behave.

Thus, I think we should first define the expected behavior. In what cases it should fail and in which it shouldn't. It's probably as easy as in "In any case the connection can't be successfully established, the sensor will return false.", but there might be exceptions I currently overlook.

This expectation should be put into the documentation, preferably direclty into the class as doc block or in the general documentation about each sensor (see #15).

2018-12-12 11:07 UTC, ravage84 requested changes

2018-12-12 11:07 UTC, ravage84 commented on src/Heartbeat/Sensor/DBConnection.php
>              $hasDBConnection = false;
If we return early within the try block, we should return in the catch  block, too.

2018-12-14 10:06 UTC, liviascapin commented
I mean that you would probably expect the 'DB Connection Sensor' to show whether the database is, you know, connected and running.

What the sensor did do however, was just getting the connection information, which always works, even if the database is not running. This makes the Sensor basically useless and is not what one would expect and not how the sensor worked in 2.x, hence I tried to mend that.

2018-12-14 10:44 UTC, merged